# Assignment 8
Using any dataset that has a categorical feature that needs to be predicted, use several algorithms, preprocessing techniques, feature extraction techniques to fit the data to the model and show the accuracy, confusion matrix, and the classification report. G
https://www.kaggle.com/ntnu-testimon/paysim1
https://www.kaggle.com/joniarroba/noshowappointments
https://archive.ics.uci.edu/ml/datasets.html?format=&task=cla&att=&area=&numAtt=&numIns=&type=&sort=nameUp&view=table
https://archive.ics.uci.edu/ml/datasets/default+of+credit+card+clients
https://archive.ics.uci.edu/ml/datasets/Adult

In [432]:
import pandas as pd
import seaborn as sns
import numpy as np
from sklearn import preprocessing
from sklearn.svm import LinearSVC
from sklearn.linear_model import LogisticRegression

In [433]:
#selected "Adult" database from https://archive.ics.uci.edu/ml/datasets/Adult
headerlist = ["age", "workclass", "fnlwgt", "education", "education-num", "marital-status", "occupation", "relationship", "race", "sex", "capital-gain", "capital-loss", "hours-per-week", "native-country", "income"]
adult = pd.read_csv("adult.data.txt", header=None, names = headerlist)

In [434]:
adult['native-country'].replace(to_replace = "-", value = " ", inplace = True, regex = True)

In [435]:
adult.dropna(inplace=True)

In [436]:
adult.head()

age          workclass  fnlwgt   education  education-num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loss  hours-per-week  native-country  income  
0          2174             0              40   United States   <=50K  
1             0             0              13   United States   <=50K  
2             0             0              40   United States   <=50K  
3             0             0              40   United States   <=50K  
4             0             0              40            Cuba   <=50K

Preprocessing Techniques

In [437]:
adult = pd.get_dummies(adult, columns=["sex", "income", "workclass", "marital-status", "race"])

In [438]:
adult['unitedstates'] = 1

In [439]:
adult.loc[adult['native-country'] != " United States", "unitedstates"] = 0

In [440]:
adult.keys()

Index(['age', 'fnlwgt', 'education', 'education-num', 'occupation',
       'relationship', 'capital-gain', 'capital-loss', 'hours-per-week',
       'native-country', 'sex_ Female', 'sex_ Male', 'income_ <=50K',
       'income_ >50K', 'workclass_ ?', 'workclass_ Federal-gov',
       'workclass_ Local-gov', 'workclass_ Never-worked', 'workclass_ Private',
       'workclass_ Self-emp-inc', 'workclass_ Self-emp-not-inc',
       'workclass_ State-gov', 'workclass_ Without-pay',
       'marital-status_ Divorced', 'marital-status_ Married-AF-spouse',
       'marital-status_ Married-civ-spouse',
       'marital-status_ Married-spouse-absent',
       'marital-status_ Never-married', 'marital-status_ Separated',
       'marital-status_ Widowed', 'race_ Amer-Indian-Eskimo',
       'race_ Asian-Pac-Islander', 'race_ Black', 'race_ Other', 'race_ White',
       'unitedstates'],
      dtype='object')

In [441]:
adult.groupby([adult['sex_ Female'], adult['education-num']]).count

<bound method DataFrameGroupBy.count of <pandas.core.groupby.groupby.DataFrameGroupBy object at 0x1a18ec8400>>

In [442]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

label_encoder = LabelEncoder()

In [443]:
nativecountry = label_encoder.fit_transform(adult['native-country'])

In [444]:
adult.head()

age  fnlwgt   education  education-num          occupation    relationship  \
0   39   77516   Bachelors             13        Adm-clerical   Not-in-family   
1   50   83311   Bachelors             13     Exec-managerial         Husband   
2   38  215646     HS-grad              9   Handlers-cleaners   Not-in-family   
3   53  234721        11th              7   Handlers-cleaners         Husband   
4   28  338409   Bachelors             13      Prof-specialty            Wife   

   capital-gain  capital-loss  hours-per-week  native-country      ...       \
0          2174             0              40   United States      ...        
1             0             0              13   United States      ...        
2             0             0              40   United States      ...        
3             0             0              40   United States      ...        
4             0             0              40            Cuba      ...        

   marital-status_ Married-spouse-absent  marital-status_ Never-married  \
0                                      0                              1   
1                                      0                              0   
2                                      0                              0   
3                                      0                              0   
4                                      0                              0   

   marital-status_ Separated  marital-status_ Widowed  \
0                          0                        0   
1                          0                        0   
2                          0                        0   
3                          0                        0   
4                          0                        0   

   race_ Amer-Indian-Eskimo  race_ Asian-Pac-Islander  race_ Black  \
0                         0                         0            0   
1                         0                         0            0   
2                         0                         0            0   
3                         0                         0            1   
4                         0                         0            1   

   race_ Other  race_ White  unitedstates  
0            0            1             1  
1            0            1             1  
2            0            1             1  
3            0            0             1  
4            0            0             0  

[5 rows x 36 columns]

In [445]:
adult.keys()

Index(['age', 'fnlwgt', 'education', 'education-num', 'occupation',
       'relationship', 'capital-gain', 'capital-loss', 'hours-per-week',
       'native-country', 'sex_ Female', 'sex_ Male', 'income_ <=50K',
       'income_ >50K', 'workclass_ ?', 'workclass_ Federal-gov',
       'workclass_ Local-gov', 'workclass_ Never-worked', 'workclass_ Private',
       'workclass_ Self-emp-inc', 'workclass_ Self-emp-not-inc',
       'workclass_ State-gov', 'workclass_ Without-pay',
       'marital-status_ Divorced', 'marital-status_ Married-AF-spouse',
       'marital-status_ Married-civ-spouse',
       'marital-status_ Married-spouse-absent',
       'marital-status_ Never-married', 'marital-status_ Separated',
       'marital-status_ Widowed', 'race_ Amer-Indian-Eskimo',
       'race_ Asian-Pac-Islander', 'race_ Black', 'race_ Other', 'race_ White',
       'unitedstates'],
      dtype='object')

In [446]:
adult['income_ >50K'].value_counts(normalize=True)

0    0.75919
1    0.24081
Name: income_ >50K, dtype: float64

In [447]:
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.neighbors import KNeighborsClassifier

# Logistic Regression

In [448]:
feature_cols = ['unitedstates','sex_ Male','sex_ Female','age','workclass_ Private','workclass_ State-gov','education-num','capital-gain','capital-loss','marital-status_ Married-AF-spouse','marital-status_ Never-married','race_ White','race_ Black']
X = adult[feature_cols]
y = adult['income_ >50K']

model = LogisticRegression()
model.fit(X, y)
adult['pred'] = model.predict(X)

accuracy_score(adult['income_ >50K'], adult.pred.round())

0.8320997512361414

In [449]:
confusion_matrix(adult['income_ >50K'], adult.pred.round())

array([[22981,  1739],
       [ 3728,  4113]])

In [450]:
print(classification_report(adult['income_ >50K'], adult.pred.round()))

             precision    recall  f1-score   support

          0       0.86      0.93      0.89     24720
          1       0.70      0.52      0.60      7841

avg / total       0.82      0.83      0.82     32561



# LinearSVC

In [451]:
feature_cols = ['sex_ Male', 'age','workclass_ Self-emp-not-inc',]
X = adult[feature_cols]
y = adult['income_ >50K']

model = LinearSVC()
model.fit(X, y)
adult['pred'] = model.predict(X)

accuracy_score(adult['income_ >50K'], adult.pred.round())

0.7591904425539756

In [452]:
confusion_matrix(adult['income_ >50K'], adult.pred.round())

array([[24720,     0],
       [ 7841,     0]])

In [453]:
print(classification_report(adult['income_ >50K'], adult.pred.round()))

             precision    recall  f1-score   support

          0       0.76      1.00      0.86     24720
          1       0.00      0.00      0.00      7841

avg / total       0.58      0.76      0.66     32561



/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


# KNeighborsClassifier

In [454]:
feature_cols = ['sex_ Male', 'age','workclass_ Self-emp-not-inc',]
X = adult[feature_cols]
y = adult['income_ >50K']

model = KNeighborsClassifier(100)
model.fit(X, y)
adult['pred'] = model.predict(X)

accuracy_score(adult['income_ >50K'], adult.pred.round())

0.7606645987531095

In [455]:
confusion_matrix(adult['income_ >50K'], adult.pred.round())

array([[23321,  1399],
       [ 6394,  1447]])

In [456]:
print(classification_report(adult['income_ >50K'], adult.pred.round()))

             precision    recall  f1-score   support

          0       0.78      0.94      0.86     24720
          1       0.51      0.18      0.27      7841

avg / total       0.72      0.76      0.72     32561



Logistic regression model seems to be the most accurate, and has the best outcome on the confusion matrix. While the model could still be improved, there were quite a few correct predictions for those above and below $50k. 